### ISSUE TITLE
 importing BasicClaient module to the project, which is right in directory (python 3.4) - No module named 'basic'

### ISSUE THREAD

**Issue by Armin7Taheri** [sourcesimian/pyTelegramBotAPI#1]
Hi there, i'm almost newbie to Python, i've installed this package to site-package and i have it as two folders of : TelegramBotAPI-0.1-py3.4.egg-info and TelegramBotAPI, but when i want run this script:
from TelegramBotAPI.client.basic import BasicClient
I get this error:
  File "C:\Python34\lib\site-packages\TelegramBotAPI\client__init__.py", line 1, in <module>
    from basic import BasicClient
ImportError: No module named 'basic'

**Comment by adilkhash** [comment]
Currently this module does not support Python 3.x

**Comment by sourcesimian** [comment]
Now migrated to Python 3.x
